/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ColaSucursales.Cola;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Randall
 */
public class VistaSucursales extends javax.swing.JFrame {

    /**
     * Creates new form VistaSucursales
     */
    private String n;
    private String p;
    private String c;
    private String ha;
    private String cp;

    public VistaSucursales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblEditar = new javax.swing.JButton();
        lblEliminar = new javax.swing.JButton();
        lblSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblNomSu = new javax.swing.JLabel();
        txtNomSu = new javax.swing.JTextField();
        lblProvin = new javax.swing.JLabel();
        txtProvincia = new javax.swing.JTextField();
        lblCanton = new javax.swing.JLabel();
        txtCanton = new javax.swing.JTextField();
        lblHorario = new javax.swing.JLabel();
        txtHorario = new javax.swing.JTextField();
        CantP = new javax.swing.JLabel();
        txtCantP = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(43, 56, 97));

        jScrollPane2.setBackground(new java.awt.Color(5, 12, 24));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Sucursal", "Provincia", "Canton", "Horario", "Numero de empleados"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(5, 12, 24));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cargar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(43, 56, 97));

        lblEditar.setBackground(new java.awt.Color(5, 12, 24));
        lblEditar.setForeground(new java.awt.Color(255, 255, 255));
        lblEditar.setText("Guardar Cambios");
        lblEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditarMouseClicked(evt);
            }
        });
        lblEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblEditarActionPerformed(evt);
            }
        });

        lblEliminar.setBackground(new java.awt.Color(5, 12, 24));
        lblEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminar.setText("Eliminar");
        lblEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarMouseClicked(evt);
            }
        });

        lblSalir.setBackground(new java.awt.Color(5, 12, 24));
        lblSalir.setForeground(new java.awt.Color(255, 255, 255));
        lblSalir.setText("Salir");

        jPanel3.setBackground(new java.awt.Color(43, 56, 97));

        lblNomSu.setForeground(new java.awt.Color(255, 255, 255));
        lblNomSu.setText("Nombre de la Sucursal");

        txtNomSu.setBackground(new java.awt.Color(5, 12, 24));
        txtNomSu.setForeground(new java.awt.Color(255, 255, 255));

        lblProvin.setForeground(new java.awt.Color(255, 255, 255));
        lblProvin.setText("Provincia");

        txtProvincia.setBackground(new java.awt.Color(5, 12, 24));
        txtProvincia.setForeground(new java.awt.Color(255, 255, 255));

        lblCanton.setForeground(new java.awt.Color(255, 255, 255));
        lblCanton.setText("Canton");

        txtCanton.setBackground(new java.awt.Color(5, 12, 24));
        txtCanton.setForeground(new java.awt.Color(255, 255, 255));

        lblHorario.setForeground(new java.awt.Color(255, 255, 255));
        lblHorario.setText("Horario de atencion");

        txtHorario.setBackground(new java.awt.Color(5, 12, 24));
        txtHorario.setForeground(new java.awt.Color(255, 255, 255));

        CantP.setForeground(new java.awt.Color(255, 255, 255));
        CantP.setText("Cantidad de puestos de atencion");

        txtCantP.setBackground(new java.awt.Color(5, 12, 24));
        txtCantP.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNomSu)
                    .addComponent(lblProvin)
                    .addComponent(lblCanton)
                    .addComponent(lblHorario)
                    .addComponent(CantP)
                    .addComponent(txtNomSu, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(txtProvincia)
                    .addComponent(txtCanton)
                    .addComponent(txtHorario)
                    .addComponent(txtCantP))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblNomSu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomSu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProvin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCanton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CantP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(lblEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEliminar)
                    .addComponent(lblSalir)
                    .addComponent(lblEditar))
                .addGap(51, 51, 51))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 51));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Editar/Eliminar Sucursales");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(120, 120, 120))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEditarActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Cola cola = new Cola();
        try {
            FileInputStream miArchivo2;
            miArchivo2 = new FileInputStream("Sucursal.su");
            ObjectInputStream input = new ObjectInputStream(miArchivo2);
            Cola vcola = (Cola) input.readObject();
            input.close();
            cola = vcola;
            miArchivo2.close();
        } catch (Exception ex) {
            System.out.println("Exception: " + ex.getMessage());

        }
        mostrarT(cola);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here

        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        int column = source.columnAtPoint(evt.getPoint());
        n = source.getModel().getValueAt(row, 0) + "";
        p = source.getModel().getValueAt(row, 1) + "";
        c = source.getModel().getValueAt(row, 2) + "";
        ha = source.getModel().getValueAt(row, 3) + "";
        cp = source.getModel().getValueAt(row, 4) + "";

        this.UpdateDatos(n, p, c, ha, cp);


    }//GEN-LAST:event_jTable1MouseClicked

    private void lblEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseClicked
        // TODO add your handling code here:
        Cola cola = new Cola();
        try {
            FileInputStream miArchivo2;
            miArchivo2 = new FileInputStream("Sucursal.su");
            ObjectInputStream input = new ObjectInputStream(miArchivo2);
            Cola vcola = (Cola) input.readObject();
            input.close();
            cola = vcola;
            miArchivo2.close();
        } catch (Exception ex) {
            System.out.println("Exception: " + ex.getMessage());

        }

        try {

            FileOutputStream miArchivo = new FileOutputStream("Sucursal.su");
            ObjectOutputStream output = new ObjectOutputStream(miArchivo);
            output.writeObject(cola.EliminarSucursal(txtNomSu.getText(), txtProvincia.getText(), txtCanton.getText(), txtHorario.getText(), txtCantP.getText()));
            output.close();
            miArchivo.close();
            JOptionPane.showMessageDialog(null, "Se elimino correctamente en la Sucursal");
            cola.listarCola();
        } catch (Exception ex) {
            System.out.println("Exception: " + ex.getMessage());
        }


    }//GEN-LAST:event_lblEliminarMouseClicked

    private void lblEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditarMouseClicked
        // TODO add your handling code here:

        Cola cola = new Cola();
        try {
            FileInputStream miArchivo2;
            miArchivo2 = new FileInputStream("Sucursal.su");
            ObjectInputStream input = new ObjectInputStream(miArchivo2);
            Cola vcola = (Cola) input.readObject();
            input.close();
            cola = vcola;
            miArchivo2.close();
        } catch (Exception ex) {
            System.out.println("Exception: " + ex.getMessage());
        }
        Cola ColaSE = cola.EditarDatos(n, p, c, ha, cp, txtNomSu.getText(), txtProvincia.getText(), txtCanton.getText(), txtHorario.getText(), txtCantP.getText());
        try {

            FileOutputStream miArchivo = new FileOutputStream("Sucursal.su");
            ObjectOutputStream output = new ObjectOutputStream(miArchivo);
            output.writeObject(ColaSE);
            output.close();
            miArchivo.close();
            JOptionPane.showMessageDialog(null, "Se edito correctamente en la Sucursal");
            cola.listarCola();
        } catch (Exception ex) {
            System.out.println("Exception: " + ex.getMessage());
        }


    }//GEN-LAST:event_lblEditarMouseClicked
    public void mostrarT(Cola cola) {
        String matriz[][] = new String[cola.getSize()][5];
        for (int i = 0; i < cola.getSize(); i++) {
            matriz[i][0] = cola.getFrente().getSucursal().getNomSu();
            matriz[i][1] = cola.getFrente().getSucursal().getProvincia();
            matriz[i][2] = cola.getFrente().getSucursal().getCanton();
            matriz[i][3] = cola.getFrente().getSucursal().getHorarioAten();
            matriz[i][4] = cola.getFrente().getSucursal().getCantPuesto();
            cola.setFrente(cola.getFrente().getSiguiente());
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "Nombre Sucursal", "Provincia", "Canton", "Horario", "Cantidad de Puestos"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

    }

    public void UpdateDatos(String NomSu, String Provincia, String Canton, String HorarioAten, String CantPuesto) {
        //Abrir el archivo y sacar la cola

        txtNomSu.setText(NomSu);
        txtCantP.setText(CantPuesto);
        txtHorario.setText(HorarioAten);
        txtProvincia.setText(Provincia);
        txtCanton.setText(Canton);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaSucursales().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CantP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCanton;
    private javax.swing.JButton lblEditar;
    private javax.swing.JButton lblEliminar;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblNomSu;
    private javax.swing.JLabel lblProvin;
    private javax.swing.JButton lblSalir;
    private javax.swing.JTextField txtCantP;
    private javax.swing.JTextField txtCanton;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtNomSu;
    private javax.swing.JTextField txtProvincia;
    // End of variables declaration//GEN-END:variables
}
